travis:
  secure:
    BINSTAR_TOKEN: ery85RN1O0x39Zqo0kT+T5vJF/H6ewmJjyQNm8BiVFu8HTLDKOqepg8HBJxM9xo6E82iAwOaK+r8Ng8mFIebIoUCShXaytCVNpoqpMp75v/gIqRW6Oc1FoZqtTtk17+s+d4ckx1eX9qhmqd9BPpDQ21KYOl+Dm3DqLT8YfEPE+W0EcpFJRd6UGLCBWl4fxFPCLBTLuY0zAgNEArrbVkxU8EJvqpOc1YhR5mzN5l+m+j56KtjkHThC7AUq6YTl8WK25zaEirFx+prT8rncrjfd5G/TtbDzuqIIpY1NQ1a79+tKsGF6BcWvzV/wL3RhJrPLYAqo+TJCZQIVzuT1aCb3lh9YYtno+pAouaf0/DcRqSna8LAueVsFCocznzYxf38YjcUHAz6mVGj66m99724rzEPMX7xIdOXWEbFcQhP7/FK8oqmnSBCTO/JQA7v3ViBzZklMvtOrQrOP3yOXZtO5W9ytfia5IWTPsbsh8yzXQCuf1/m4BJ5CRYAR9kEFNipDEdhYyfGwdN7rRp6+SfNVTelUqzsN3Ttf5r6avRGuNeku7hJLbxIL1q1lEm8/70hNJUrl/5Q6sjmHpmop4NH0LTypXcUTbv2Yqc6Kcl8POYJC4TFlss5TUH628sxAW/VccehU3brV5l14/UTJBTYOZRe0cX3y59rxE6/GO3APMI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
